In [3]:
import numpy as np
b = np.arange(3)
print(b)
print(np.exp(b))  # e^x
print(np.sqrt(b)) # 开根

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [24]:
a = np.floor(3.5)  # 向下取整 取一个不大于当前数字的熟
a = np.floor(10*np.random.random((3,4)))
print(a)
print(a.ravel()) # 将多维数组转换为一维数组  
a.ravel()[1] = 99 # 会改变源数组数据
a.shape = (6,2)
print(a)
print(a.flatten()) # flatten函数返回的是拷贝
a.flatten()[1] = -1 # 不改变源数据
print(a.T) # a的转秩


[[6. 8. 8. 0.]
 [6. 2. 4. 0.]
 [6. 3. 3. 4.]]
[6. 8. 8. 0. 6. 2. 4. 0. 6. 3. 3. 4.]
[[ 6. 99.]
 [ 8.  0.]
 [ 6.  2.]
 [ 4.  0.]
 [ 6.  3.]
 [ 3.  4.]]
[ 6. 99.  8.  0.  6.  2.  4.  0.  6.  3.  3.  4.]
[[ 6.  8.  6.  4.  6.  3.]
 [99.  0.  2.  0.  3.  4.]]


In [28]:
a = np.floor(10*np.random.random((6,2)))  # 6 * 2 的矩阵 0~1之间的float
print(a)
print(a.resize((2,6)))
print(a)
print(a.reshape((6,2)))

[[1. 9.]
 [0. 1.]
 [8. 3.]
 [7. 8.]
 [2. 0.]
 [6. 6.]]
None
[[1. 9. 0. 1. 8. 3.]
 [7. 8. 2. 0. 6. 6.]]
[[1. 9.]
 [0. 1.]
 [8. 3.]
 [7. 8.]
 [2. 0.]
 [6. 6.]]


In [35]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)
print(np.hstack((a,b))) #在水平方向上平铺
print(np.vstack((a,b))) #在垂直方向上堆叠

[[7. 2.]
 [2. 6.]]
[[3. 8.]
 [9. 7.]]
[[7. 2. 3. 8.]
 [2. 6. 9. 7.]]
[[7. 2.]
 [2. 6.]
 [3. 8.]
 [9. 7.]]


In [48]:
a = np.floor(10*np.random.random((2,12)))
print(a)
# print(np.hsplit(a,3)) # 沿着水平方向切割
print(np.hsplit(a,(3,4)) )
a = np.floor(10*np.random.random((12,2)))
print(np.vsplit(a,3))

[[1. 6. 8. 5. 0. 4. 0. 3. 7. 5. 3. 0.]
 [9. 2. 5. 2. 8. 7. 3. 0. 7. 8. 8. 3.]]
[array([[1., 6., 8.],
       [9., 2., 5.]]), array([[5.],
       [2.]]), array([[0., 4., 0., 3., 7., 5., 3., 0.],
       [8., 7., 3., 0., 7., 8., 8., 3.]])]
[array([[0., 3.],
       [0., 0.],
       [9., 5.],
       [9., 6.]]), array([[9., 0.],
       [6., 7.],
       [6., 2.],
       [0., 8.]]), array([[6., 0.],
       [0., 7.],
       [0., 8.],
       [8., 6.]])]


In [51]:
a = np.arange(12)
b = a
print(b is a) # b与a控制着同一个向量 只是名字不一样
b.shape = (3,4)
print(a)

True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
c = a.view() # c是一个新的向量 但a c两个对象共享相同的数据
print(c is a)
c.shape = 2,6
c[0,4] = 1234
print(c)
print(a)

False
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [57]:
d = a.copy()  # The copy method makes a complete copy of the array and its data.
print(d is a)
d[0,0] = 9999
print(d)
print(a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
